version = 0.1

[default.deploy.parameters]
stack_name = "meet-u"
resolve_s3 = true
s3_prefix = "meet-u"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "LineLoginChannelId=\"2011216820\" LiffId=\"2011216820-mu8c5U6v\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
